import Head from 'next/head'
import { Menu, Layout, theme, MenuProps } from 'antd'
import {
  NodeIndexOutlined,
  DatabaseOutlined,
  CodepenOutlined
} from '@ant-design/icons';
import React from 'react';
import { useRouter } from 'next/router';

const { Sider, Content, Header } = Layout;

type MenuItem = Required<MenuProps>['items'][number];

const items: MenuItem[] = [
  getItem('Onboarding', 'onboarding', null, [
    getItem('Corporate (Atomic)', '/'),
    getItem('Individual (Atomic)', 2),
  ]),
  getItem('Sql', 'Sql', null, [
    getItem('BigQuery', 3),
    getItem('MEA', '/mea'),
    getItem('Pricing', '/pricing'),
    getItem('Billing Transactions', '/billing-transactions'),
  ]),
  getItem('Code Snippets', 'code', null, [
    getItem('Package', 5),
    getItem('Service', 6),
    getItem('Schema', 7),
    getItem('Controller', 8),
    getItem('Repository', 9),
    getItem('Routes', 10),
  ]),
  getItem('Tools', '/tools'),
];

function getItem(
  label: React.ReactNode,
  key: React.Key,
  icon?: React.ReactNode,
  children?: MenuItem[],
): MenuItem {
  return {
    key,
    icon,
    children,
    label,
  } as MenuItem;
}

export function DashboardLayout({ children }: any) {

  const router = useRouter();
  const {
    token: { colorBgContainer },
  } = theme.useToken();

  const handleSidebarChange = (e: any) => {
    router.push(e.key);
  }

  return <>
    <Head>
      <title>ZAMP | OPS</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
      <Sider
        breakpoint="lg"
        collapsedWidth="0"
        collapsible={true}
      >
        <div style={{ color: '#fff', padding: '10px', fontWeight: 'bold', textAlign: 'center' }}>
          <img src='/zamp.png' alt='logo' />
        </div>
        <Menu theme="dark" onSelect={(e) => handleSidebarChange(e)} defaultSelectedKeys={['1']} mode="inline" items={items} />
      </Sider>
      <Layout >
        <Header style={{ padding: 0, background: colorBgContainer, position: 'sticky' }} />
        <Content style={{ margin: '24px 16px 0', overflow: 'scroll', height: '100vh' }}>
          {children}
        </Content>
      </Layout>
    </Layout>
  </>
}