import Head from 'next/head'
import { Menu, Layout, theme, MenuProps } from 'antd'
import {
  UserOutlined,
  NodeIndexOutlined,
  DatabaseOutlined,
  CodepenOutlined
} from '@ant-design/icons';
import React from 'react';
import { AtomicOnboarding } from '../components/atomic_onboarding';


const { Sider, Content, Header } = Layout;
type MenuItem = Required<MenuProps>['items'][number];

const items: MenuItem[] = [
  getItem('Onboarding', 'onboarding', <NodeIndexOutlined />, [
    getItem('Corporate', 1),
    getItem('Individual', 2),
  ]),
  getItem('Sql', 'Sql', <DatabaseOutlined />, [
    getItem('BigQuery', 3),
    getItem('Individual', 4),
  ]),
  getItem('Code Snippets', 'code', <CodepenOutlined />, [
    getItem('Package', 5),
    getItem('Service', 6),
    getItem('Schema', 7),
    getItem('Controller', 7),
    getItem('Repository', 7),
    getItem('Routes', 7),
  ]),
];

function getItem(
  label: React.ReactNode,
  key: React.Key,
  icon?: React.ReactNode,
  children?: MenuItem[],
): MenuItem {
  return {
    key,
    icon,
    children,
    label,
  } as MenuItem;
}

export default function Home() {

  const {
    token: { colorBgContainer },
  } = theme.useToken();

  return (
    <>
      <Head>
        <title>ZAMP | OPS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <Sider
            breakpoint="lg"
            collapsedWidth="0"

            collapsible={true}
          >
            <div>ZAMP</div>
            <Menu theme="dark" onSelect={(e) => console.log(e)} defaultSelectedKeys={['1']} mode="inline" items={items} />
          </Sider>
          <Layout >
            <Header style={{ padding: 0, background: colorBgContainer, position: 'sticky' }} />
            <Content style={{ margin: '24px 16px 0', overflow: 'scroll', height: '100vh' }}>
              <AtomicOnboarding />
            </Content>
          </Layout>
        </Layout>
      </main>
    </>
  )
}
